// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPIALabPrograWebTienda.Models.dbModels;

#nullable disable

namespace ProyectoPIALabPrograWebTienda.Migrations
{
    [DbContext(typeof(ProyectoPIALabPrograWebTiendaContext))]
    partial class ProyectoPIALabPrograWebTiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Carrito", b =>
                {
                    b.Property<int>("Idusuario")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("Idusuario", "Idproducto");

                    b.HasIndex("Idproducto");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Categorium", b =>
                {
                    b.Property<int>("Idcategoria")
                        .HasColumnType("int")
                        .HasColumnName("IDCategoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Idcategoria")
                        .HasName("PK__Categori__70E82E285CE274D3");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.DetallesVentum", b =>
                {
                    b.Property<int>("Idventa")
                        .HasColumnType("int")
                        .HasColumnName("IDVenta");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money");

                    b.HasKey("Idventa", "Idproducto");

                    b.HasIndex("Idproducto");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproducto"), 1L, 1);

                    b.Property<int>("Idcategoria")
                        .HasColumnType("int")
                        .HasColumnName("IDCategoria");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("money");

                    b.HasKey("Idproducto");

                    b.HasIndex("Idcategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Ventum", b =>
                {
                    b.Property<int>("Idventa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idventa"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("money");

                    b.HasKey("Idventa");

                    b.HasIndex("Idusuario");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Carrito", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.Producto", "IdproductoNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("Idproducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Carrito_Productos");

                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", "IdusuarioNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("Idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Carrito_Usuario");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.DetallesVentum", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.Producto", "IdproductoNavigation")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("Idproducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVenta_Productos");

                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.Ventum", "IdventaNavigation")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("Idventa")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVenta_Venta");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdventaNavigation");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Producto", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.Categorium", "IdcategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Idcategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categoria");

                    b.Navigation("IdcategoriaNavigation");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Ventum", b =>
                {
                    b.HasOne("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", "IdusuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Usuario");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.ApplicationUser", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("ProyectoPIALabPrograWebTienda.Models.dbModels.Ventum", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
